# 2.1 Data Manipulation

In [36]:
import torch

In [37]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [38]:
x.numel()

12

In [39]:
x.shape

torch.Size([12])

In [40]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [41]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [42]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [43]:
torch.randn(3, 4, dtype=torch.float32, generator=torch.Generator().manual_seed(2))

tensor([[ 0.3923, -0.2236, -0.3195, -1.2050],
        [ 1.0445, -0.6332,  0.5731,  0.5409],
        [-0.3919, -1.0427,  1.3186,  0.7476]])

In [44]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [45]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [46]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [47]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [48]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [49]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [50]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([
    [2.0, 1, 4, 3], 
    [1, 2, 3, 4], 
    [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [51]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [52]:
X.sum()

tensor(66.)

In [53]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [54]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [55]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [56]:
Z = torch.zeros_like(Y)
print(f'id(Z) = {id(Z)}')
Z[:] = X + Y
print(f'id(Z) = {id(Z)}')

id(Z) = 4978268336
id(Z) = 4978268336


In [57]:
before = id(X)
X += Y
id(X) == before

True

In [58]:
import numpy as np
A = np.array([1, 2, 3])
B = torch.tensor(A)
print((A, B))
B[1] = 4
print((A, B))
B.numpy()

(array([1, 2, 3]), tensor([1, 2, 3]))
(array([1, 2, 3]), tensor([1, 4, 3]))


array([1, 4, 3])

In [59]:
A = np.array([1, 2, 3])
B = torch.from_numpy(A)
print((A, B))
B[1] = 4
print((A, B))
B.numpy()

(array([1, 2, 3]), tensor([1, 2, 3]))
(array([1, 4, 3]), tensor([1, 4, 3]))


array([1, 4, 3])

In [60]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# Exercises

In [61]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [62]:
X < Y, X > Y

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [63]:
X = torch.arange(12).reshape((3, 4))
Y = torch.arange(4).reshape((1, 4))
print((X, Y))
X + Y

(tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), tensor([[0, 1, 2, 3]]))


tensor([[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]])

In [64]:
X = torch.arange(12).reshape((3, 4))
Y = torch.arange(4)
print((X, Y))
X + Y

(tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), tensor([0, 1, 2, 3]))


tensor([[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]])

In [65]:
X = torch.arange(12).reshape((3, 4))
Y = torch.arange(3).reshape(3, 1)
print((X, Y))
X + Y

(tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), tensor([[0],
        [1],
        [2]]))


tensor([[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]])

In [66]:
X = torch.arange(12).reshape((3, 4))
Y = torch.arange(3).reshape((3, 1))
print((X, Y))
X + Y

(tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), tensor([[0],
        [1],
        [2]]))


tensor([[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]])

In [67]:
X = torch.arange(12).reshape((3, 4))
Y = torch.arange(4).reshape((4, 1))
print((X, Y))
X + Y

(tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), tensor([[0],
        [1],
        [2],
        [3]]))


RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0