In [62]:
import torch

In [63]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [64]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [65]:
x[2]

tensor(2)

In [66]:
len(x)

3

In [67]:
x.shape

torch.Size([3])

In [68]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [69]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [70]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [71]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [72]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [73]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [74]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, a * X

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

In [75]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [76]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [77]:
print((A.shape, A.sum())) 
print((A.sum(axis=0), A.sum(axis=1)))

(torch.Size([2, 3]), tensor(15.))
(tensor([3., 5., 7.]), tensor([ 3., 12.]))


In [78]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [79]:
A.shape, A.sum(axis=0, keepdims=True).shape

(torch.Size([2, 3]), torch.Size([1, 3]))

In [80]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [81]:
A.shape, A.sum(axis=1, keepdims=True).shape

(torch.Size([2, 3]), torch.Size([2, 1]))

In [82]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()

tensor(True)

In [83]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [84]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [85]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [86]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [87]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [88]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [89]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [90]:
torch.sum(x * y)

tensor(3.)

In [91]:
A, x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]))

In [92]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [93]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [94]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [95]:
torch.abs(u).sum()

tensor(7.)

In [96]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [97]:
X = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
len(X), X.numel()

(2, 24)

In [98]:
X, X.sum(axis=1)

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[12., 15., 18., 21.],
         [48., 51., 54., 57.]]))

In [99]:
X / X.sum(axis=1, keepdims=True)

tensor([[[0.0000, 0.0667, 0.1111, 0.1429],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.6667, 0.6000, 0.5556, 0.5238]],

        [[0.2500, 0.2549, 0.2593, 0.2632],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.4167, 0.4118, 0.4074, 0.4035]]])

In [100]:
A / A.sum(axis=1, keepdims=True)

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [101]:
X

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [102]:
X.sum(), X.sum(axis=0), X.sum(axis=1), X.sum(axis=2)

(tensor(276.),
 tensor([[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]),
 tensor([[12., 15., 18., 21.],
         [48., 51., 54., 57.]]),
 tensor([[ 6., 22., 38.],
         [54., 70., 86.]]))

In [103]:
X = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
X

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [104]:
torch.linalg.norm(X)  # Frobenius norm by default

tensor(65.7571)

先把尺寸写清楚：

* $A\in\mathbb R^{2^{10}\times 2^{16}}=1024\times 65536$
* $B\in\mathbb R^{2^{16}\times 2^{5}}=65536\times 32$
* $C\in\mathbb R^{2^{5}\times 2^{14}}=32\times 16384$
* 结果 $ABC\in\mathbb R^{1024\times 16384}$

## 计算量（以乘法次数计，FLOPs 约为它的 2 倍）

* $(AB)C$:

  * $AB:\ 1024\times 65536\times 32=2^{10+16+5}=2^{31}=2{,}147{,}483{,}648$
  * $(AB)C:\ 1024\times 32\times 16384=2^{10+5+14}=2^{29}=536{,}870{,}912$
  * 总计 $=2^{31}+2^{29}=5\times 2^{29}=2{,}684{,}354{,}560$ 乘法
    （≈ **5.37×10⁹ FLOPs**）

* $A(BC)$:

  * $BC:\ 65536\times 32\times 16384=2^{16+5+14}=2^{35}=34{,}359{,}738{,}368$
  * $A(BC):\ 1024\times 65536\times 16384=2^{10+16+14}=2^{40}=1{,}099{,}511{,}627{,}776$
  * 总计 $=2^{35}+2^{40}=33\times 2^{35}=1{,}133{,}871{,}366{,}144$ 乘法
    （≈ **2.27×10¹² FLOPs**）

**比值**：$\dfrac{1.1339\times 10^{12}}{2.684\times 10^{9}}\approx 422.4$。
→ $(AB)C$ 约 **快 400+ 倍**。

## 中间结果的内存

* $(AB)C$ 的中间矩阵 $AB\in\mathbb R^{1024\times 32}$：元素数 $2^{10+5}=2^{15}=32{,}768$。

  * float32 ≈ **128 KB**（float64 ≈ 256 KB）。
* $A(BC)$ 的中间矩阵 $BC\in\mathbb R^{65536\times 16384}$：元素数 $2^{16+14}=2^{30}=1{,}073{,}741{,}824$。

  * float32 ≈ **4 GB**（float64 ≈ 8 GB）。

**结论**：选择 $(AB)C$。它不仅计算量远小（\~422×），而且中间张量极小（\~128 KB vs 4–8 GB），更能命中缓存、也更可能在 GPU/内存中放得下。原因是矩阵连乘的代价取决于每一步的三维乘法尺寸 $a\times b\times c$；先把产生**较小中间维度**（这里是 $32$）的那两项相乘最划算。


In [105]:
A = torch.ones(100, 200)
B = torch.ones(100, 200)
C = torch.ones(100, 200)

(A.shape, B.shape, C.shape)

(torch.Size([100, 200]), torch.Size([100, 200]), torch.Size([100, 200]))

In [106]:
torch.hstack((A, B, C)).shape

torch.Size([100, 600])

In [107]:
torch.vstack((A, B, C)).shape

torch.Size([300, 200])

In [108]:
torch.cat((A, B, C)).shape

torch.Size([300, 200])

In [109]:
D = torch.cat((A, B, C))[100:200, :]
D.shape

torch.Size([100, 200])

In [110]:
x = torch.arange(3, dtype=torch.float32)
y = torch.ones(3, dtype=torch.float32)
x, y

(tensor([0., 1., 2.]), tensor([1., 1., 1.]))

In [111]:
torch.cat((x, y)).shape

torch.Size([6])