In [2]:
import torch
from torch import nn
from torch.nn import functional as F

In [5]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x - x.mean()

In [9]:
layer = CenteredLayer()
x = torch.tensor([1.0, 2, 3, 4, 5])
print(x.mean())
layer(x)

tensor(3.)


tensor([-2., -1.,  0.,  1.,  2.])

In [10]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

In [11]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(5.5879e-09, grad_fn=<MeanBackward0>)

In [12]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [17]:
linear = MyLinear(5, 3)
print(linear.weight, linear.bias)
print(linear.weight.shape, linear.bias.shape)

Parameter containing:
tensor([[ 0.8844, -1.1284, -1.8396],
        [ 0.9654, -0.8208,  0.3191],
        [-1.2306,  1.0651, -0.7923],
        [-0.8205, -0.2299, -1.3154],
        [ 0.1276,  0.6478, -0.4985]], requires_grad=True) Parameter containing:
tensor([ 0.3706, -0.0966,  0.4473], requires_grad=True)
torch.Size([5, 3]) torch.Size([3])


In [18]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.5721, 0.0000],
        [0.5071, 0.2436, 0.0000]])

In [19]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])